{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flyingpigs.petcore",
    "module": "petcore-sdk",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "petcore-sdk-0.2.0.aar",
          "url": "petcore-sdk-0.2.0.aar",
          "size": 29129,
          "sha512": "a94997ab26d5a45b1550fa1f178af4d45b0b827b831ee9fec81440297041678d1c3741986483d1fff869d0fa872f797836a106d9c945396e69133d1bf00d204e",
          "sha256": "c12b7a1210e9a69555b2a38e51945d2e5f873501957b83df7b3b6059e149bcb1",
          "sha1": "733e5dec31a349f218d220e0e127346facce26c9",
          "md5": "04e3bc4a9f8596f333ec4544e919c7d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "petcore-sdk-0.2.0.aar",
          "url": "petcore-sdk-0.2.0.aar",
          "size": 29129,
          "sha512": "a94997ab26d5a45b1550fa1f178af4d45b0b827b831ee9fec81440297041678d1c3741986483d1fff869d0fa872f797836a106d9c945396e69133d1bf00d204e",
          "sha256": "c12b7a1210e9a69555b2a38e51945d2e5f873501957b83df7b3b6059e149bcb1",
          "sha1": "733e5dec31a349f218d220e0e127346facce26c9",
          "md5": "04e3bc4a9f8596f333ec4544e919c7d8"
        }
      ]
    }
  ]
}
